spring:
  application:
    name: extractor
  datasource:
    url: jdbc:h2:mem:extractor
    username: appuser
    password: app@password
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
client:
  ip_validator:
    host: http://ip-api.com
feature-flag:
  enable-requester-validation: false
